### ISSUE TITLE
行中公式好像转换不了,有什么办法支持吗?

### ISSUE THREAD

**Issue by tisttsf** [JabinGP/mdout#10]
`这是一个行中公式$\frac{n!}{k!(n-k)!} = \binom{n}{k}$行中公式`
`$\frac{n!}{k!(n-k)!} = \binom{n}{k}$`
会无法正常显示
```
$$
\frac{n!}{k!(n-k)!} = \binom{n}{k}
$$
```
显示正常

**Comment by JabinGP** [comment]
测试平台：macOS 10.15.6 (19G73)
测试软件：Chrome 版本 87.0.4280.141（正式版本） (x86_64)
测试文件：test.md


`test.md` 内容如下

```md
这是一个行中公式$\frac{n!}{k!(n-k)!} = \binom{n}{k}$行中公式

$$
\frac{n!}{k!(n-k)!} = \binom{n}{k}
$$
```

转换命令 `mdout test.md -e mathjax` 得到 PDF 如下：

<img width="609" alt="WX20210131-161715@2x" src="https://user-images.githubusercontent.com/32405671/106378451-e5408600-63df-11eb-8481-6797ebf2b014.png">

两个公式都正常识别且显示，但存在缺少 `mathchoice` 库导致的显示问题，可以自行修改主题文件解决。

**Comment by tisttsf** [comment]
> 测试平台：macOS 10.15.6 (19G73)
> 测试软件：Chrome 版本 87.0.4280.141（正式版本） (x86_64)
> 测试文件：test.md
> 
> `test.md` 内容如下
> 
> ```lisp
> 这是一个行中公式$\frac{n!}{k!(n-k)!} = \binom{n}{k}$行中公式
> 
> $$
> \frac{n!}{k!(n-k)!} = \binom{n}{k}
> $$
> ```
> 
> 转换命令 `mdout test.md -e mathjax` 得到 PDF 如下：
> 
> <img alt="WX20210131-161715@2x" width="609" src="https://user-images.githubusercontent.com/32405671/106378451-e5408600-63df-11eb-8481-6797ebf2b014.png">
> 
> 两个公式都正常识别且显示，但存在缺少 `mathchoice` 库导致的显示问题，可以自行修改主题文件解决。

好的,谢谢解答
我试了两个环境,一个可以像你显示的正常显示,一个还是不行(没联网)
我查了下katex相关的问题,用\\(\frac{n!}{k!(n-k)!} = \binom{n}{k}\\)这样的形式替换$\frac{n!}{k!(n-k)!} = \binom{n}{k}$就可以正常显示了

**Comment by tisttsf** [comment]
行中公式\\(e^{i\pi}+1=0\\)行中公式行中公式行中公式

这是一个行中公式$\frac{n!}{k!(n-k)!} = \binom{n}{k}$行中公式

31312\\(\frac{n!}{k!(n-k)!} = \binom{n}{k}\\)123123

![行中公式](https://user-images.githubusercontent.com/4705133/106378775-41a4a500-63e2-11eb-9ae6-6b9c3a79ce43.PNG)

实际要两个下划线,但是github这个编辑转义了

**Comment by JabinGP** [comment]
能识别但是显示 mathchoice 的问题应该是 markdown 解析过程对于 `\\` 处理的问题，markdown 中写 `\\` 后经过转换实际生成的html 中只有 `\` ，因此使用 `\\\\` 可以解决这个问题。

test.md 测试内容

```md
这是一个行中公式$\frac{n!}{k!(n-k)!} = \\\\binom{n}{k}$行中公式

$$
\\\\frac{n!}{k!(n-k)!} = \\\\binom{n}{k}
$$
```

经过 `mdout test.md -e mathjax` 转换效果如下

![WX20210131-164618](https://user-images.githubusercontent.com/32405671/106379009-ebd0fc80-63e3-11eb-8176-c53fc26ebd71.png)

无法识别公式的问题我无法给出结论，生成 PDF 文件所使用的主题模板中的所有的 `js`, `css`, `html` 都是本地加载的，不涉及网络请求。
