### ISSUE TITLE
貌似下载的服务器出问题了，我提供个可以github加速下载的方法

### ISSUE THREAD

**Issue by hhhaiai** [JabinGP/mdout#11]
在目录里新建个release的文件夹。或者单独建个工程做release库来存放。 然后通过使用Jsdelivr加速Github下载。

普通文件：

https://cdn.jsdelivr.net/gh/<用户名>/<仓库>/<目录>
官网的示例：

// load any GitHub release, commit, or branch

// note: we recommend using npm for projects that support it

https://cdn.jsdelivr.net/gh/user/repo@version/file

// load jQuery v3.2.1

https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js

// use a version range instead of a specific version

https://cdn.jsdelivr.net/gh/jquery/jquery@3.2/dist/jquery.min.js

https://cdn.jsdelivr.net/gh/jquery/jquery@3/dist/jquery.min.js

// omit the version completely to get the latest one

// you should NOT use this in production

https://cdn.jsdelivr.net/gh/jquery/jquery/dist/jquery.min.js

// add ".min" to any JS/CSS file to get a minified version

// if one doesn't exist, we'll generate it for you

https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/src/core.min.js

// add / at the end to get a directory listing

https://cdn.jsdelivr.net/gh/jquery/jquery/
Refs:

https://www.jsdelivr.com
https://github.com/jsdelivr/jsdelivr/blob/master/README.md

**Comment by hhhaiai** [comment]
这种方式是通过CDN方式国内下载github的文件贼快  @JabinGP

**Comment by JabinGP** [comment]
服务器进行更换，链接已经失效，感谢你的建议，晚一些我会重新上传。

**Comment by hhhaiai** [comment]
这种方式下载速度很快

**Comment by hhhaiai** [comment]
关键还节约服务器费用

**Comment by hhhaiai** [comment]
比如要下载 `JabinGP/mdout `  根目录的`main.go`文件. 直接访问地址： 
https://cdn.jsdelivr.net/gh/JabinGP/mdout/main.go

**Comment by hhhaiai** [comment]
@JabinGP   http://112.74.177.253:8000/f/382a2291375045cb81fa/?dl=1  这个还是下载不了吧
