### ISSUE TITLE
怎么转换html pdf附带使用mermaid?

### ISSUE THREAD

**Issue by tisttsf** [JabinGP/mdout#12]
按照mermaid使用方法在markdown加入语句,转换成html标签的<和>会被转成 &lt; 和 &gt;
还会多出来几个<br/><p></p>标签
```html
<div class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```
`src="https://`链接会被加上`<a href=`
表格的-->的->也会被替换,这样如果转换后再用正则replace之类替换会比较繁琐
**有没有保持原html tag的方法或者其他方式使用mermaid呢?**

```html
<p>&lt;div class=“mermaid”&gt;<br/>
graph LR<br/>
A — B<br/>
B–&gt;C[fa:fa-ban forbidden]<br/>
B–&gt;D(fa:fa-spinner);<br/>
&lt;/div&gt;<br/>
&lt;script src=“<a href="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js">https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js</a>”&gt;&lt;/script&gt;<br/>
&lt;script&gt;mermaid.initialize({startOnLoad:true});&lt;/script&gt;</p>
```

**Comment by tisttsf** [comment]
应该也可以或者单独写好,然后转换成html后再将mermaid引用和表格拼到html页面里吧

**Comment by JabinGP** [comment]
Thanks for using chinese!
It's not a good idea to use `<script>` in markdown, you can add it to the template. 
Mdout don't support mermaid up to now,  but I already found some ways to implement, it may take a few days to try.

**Comment by JabinGP** [comment]
> 应该也可以或者单独写好,然后转换成html后再将mermaid引用和表格拼到html页面里吧

Add `<script>` to template and write `<div class="mermaid">` in `.md` may work when  markdown support html tag.

**Comment by JabinGP** [comment]
@tisttsf ee18263c98422fd5130da016a85789040d9ac271 已经通过修改 markdown 解析过程初步实现通过 ` ```mermaid ``` ` 的方式来使用mermaid，只需要主题文件中引入 `mermaid.js` 即可以渲染图像。
但是目前项目改动较大，代码还在整理当中，需要过一些时日才能提供新版本的程序和主题包的下载及使用说明。

**Comment by tisttsf** [comment]
> @tisttsf [ee18263](https://github.com/JabinGP/mdout/commit/ee18263c98422fd5130da016a85789040d9ac271) 已经通过修改 markdown 解析过程初步实现通过 `` ```mermaid ``` `` 的方式来使用mermaid，只需要主题文件中引入 `mermaid.js` 即可以渲染图像。
> 但是目前项目改动较大，代码还在整理当中，需要过一些时日才能提供新版本的程序和主题包的下载及使用说明。

好的谢谢回复,太感谢了!

**Comment by JabinGP** [comment]
@tisttsf 可以试试release0.7.0版本。

**Comment by tisttsf** [comment]
> @tisttsf 可以试试release0.7.0版本。
可以了 太厉害啦! 感谢!
![2021-03-05 00 11 38  41f881a9c594](https://user-images.githubusercontent.com/4705133/110000792-a723e280-7d4e-11eb-8d76-f4af9ea76c01.png)

**Comment by JabinGP** [comment]
@tisttsf 感谢你的使用。
