### ISSUE TITLE
exec: "google-chrome": executable file not found in %PATH%

### ISSUE THREAD

**Issue by xluohome** [JabinGP/mdout#2]
2019/12/01 13:39:48 ---这是你的配置文件参数---                                   
2019/12/01 13:39:48 输出路径：                                                   
2019/12/01 13:39:48 输出格式：pdf                                                
2019/12/01 13:39:48 选择主题：default                                            
2019/12/01 13:39:48 打印页面格式：a4                                             
2019/12/01 13:39:48 打印页面方向：portrait                                       
2019/12/01 13:39:48 打印页面边距：0.4                                            
2019/12/01 13:39:48 -----------------------                                      
2019/12/01 13:39:48 ---这是你的合计输入参数---                                   
2019/12/01 13:39:48 输出路径：                                                   
2019/12/01 13:39:48 输出格式：pdf                                                
2019/12/01 13:39:48 选择主题：default                                            
2019/12/01 13:39:48 打印页面格式：a4                                             
2019/12/01 13:39:48 打印页面方向：portrait                                       
2019/12/01 13:39:48 打印页面边距：0.4                                            
2019/12/01 13:39:48 -----------------------                                      
2019/12/01 13:39:48 准备开始打印                                                 
2019/12/01 13:39:48 正在加载http://www.163.com                                  
2019/12/01 13:39:48 exec: "google-chrome": executable file not found in %PATH%   
2019/12/01 13:39:48 exec: "google-chrome": executable file not found in %PATH%   
Error: exec: "google-chrome": executable file not found in %PATH%
--

**Comment by JabinGP** [comment]
1. 出现这个说明程序找不到你的chrome执行路径，一般正常安装的chrome无需任何设置都能被程序正常识别到(Linux，macOS，Windows
经过测试无异)
2. 检查你是否安装chrome
3. 如果已经安装chrome，尝试卸载重新安装最新版


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by xluohome** [comment]
一直只使用chome&nbsp; &nbsp;&nbsp;

默认安装目录： C:\Users\XXX\AppData\Local\Google\Chrome\Application\chrome.exe&nbsp; &nbsp; &nbsp;


OS:Windows 10&nbsp;
&nbsp;

PHPOSS Team!&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JabinGP"<notifications@github.com&gt;; 
发送时间: 2019年12月1日(星期天) 下午4:59
收件人: "JabinGP/mdout"<mdout@noreply.github.com&gt;; 
抄送: "472105349"<phposs@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JabinGP/mdout] exec: &quot;google-chrome&quot;: executable file not found in %PATH% (#2)



 
出现这个说明程序找不到你的chrome执行路径，一般正常安装的chrome无需任何设置都能被程序正常识别到(Linux，macOS，Windows
 经过测试无异)
 
检查你是否安装chrome
 
如果已经安装chrome，尝试卸载重新安装最新版
  
 From gitme iOS

**Comment by JabinGP** [comment]
可以贴一下Chrome的版本吗，Ubuntu16.04，Ubuntu18.04，win10，win7，macOS10.13.6，用最新版Chrome78测试的，没有出现过这样的问题，这个问题只在没有安装chrome的电脑出现过，或许是你的Chrome版本不够高？似乎chrome要使用headless模式需要59以上的版本。

**Comment by xluohome** [comment]
Google Chrome78.0.3904.108&nbsp;(正式版本)&nbsp;（64 位）&nbsp;(cohort: Stable)
修订版本4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
操作系统Windows&nbsp;10 OS Version 1809 (Build 17763.864)
JavaScriptV8&nbsp;7.8.279.23
Flash32.0.0.293 C:\Users\xxx\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.293\pepflashplayer.dll
用户代理Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
命令行"C:\Users\xxx\AppData\Local\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
可执行文件路径C:\Users\xxx\AppData\Local\Google\Chrome\Application\chrome.exe
个人资料路径C:\Users\xxx\AppData\Local\Google\Chrome\User Data\Default

&nbsp;

PHPOSS Team!&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JabinGP"<notifications@github.com&gt;; 
发送时间: 2019年12月1日(星期天) 下午5:15
收件人: "JabinGP/mdout"<mdout@noreply.github.com&gt;; 
抄送: "472105349"<phposs@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JabinGP/mdout] exec: &quot;google-chrome&quot;: executable file not found in %PATH% (#2)




可以贴一下Chrome的版本吗，Ubuntu16.04，Ubuntu18.04，win10，win7，macOS10.13.6，用最新版Chrome78测试的，没有出现过这样的问题，这个问题只在没有安装chrome的电脑出现过，或许是你的Chrome版本不够高？似乎chrome要使用headless模式需要59以上的版本。
 
&mdash;

**Comment by JabinGP** [comment]
非常抱歉，由于尝试了很多朋友的安装了chrome的电脑都无法重现错误，我很难进行故障排查，因此需要你自己花点时间进行故障排查。
另外本项目调用chrome的部分完全由开源项目[chromedp](https://github.com/chromedp/chromedp)完成，因此你可以到[chromedp](https://github.com/chromedp/chromedp)的[github](https://github.com/chromedp/chromedp)看看能否找到一些思路。
本来chromedp似乎提供了手动指定chrome路径的方法，但是经过我的测试，只要安装了chrome一般都能正常读取到执行路径，因此我并没有在mdout中加入这个功能。
鉴于你的问题，我会在下一版中加入手动指定chrome执行路径的功能，如果可以通过配置文件手动配置执行路径的话，也不会太过麻烦，可以作为解决这个问题一种方案。

**Comment by xluohome** [comment]
抽空看了一下 chromedp 的源码，
在 github.com\chromedp\chromedp@v0.5.1\allocate.go 中的 findExecPath() 中
 列了几个 chrome浏览器几种可能路径。 而我的 window10  chrome 默认安装在C:\Users\xxx\AppData\Local\Google\Chrome\Application 路径下， 因此找不到。

简单的解决方案是 在  windows 10 系统环境变量中加入 C:\Users\xxx\AppData\Local\Google\Chrome\Application 即可。

**Comment by JabinGP** [comment]
@xluohome 非常感谢你的反馈，很惭愧最近比较忙，没能抽出时间解决这个问题，非常抱歉！

**Comment by xluohome** [comment]
感谢你的项目。
