### ISSUE TITLE
[求助]markdown转带目录的PDF

### ISSUE THREAD

**Issue by hhhaiai** [JabinGP/mdout#3]
markdown转PDF正常。但是不带目录，这个功能是否可以添加上去？

**Comment by JabinGP** [comment]
markdown转pdf借助的是chrome的打印功能，本质还是md生成html，对html渲染生成pdf。
对于目录功能，我从以下几个方面进行考虑。
在chrome渲染层面，似乎chrome无法为一个普通的html文件自动生成目录，也没有提供任何的可添加方式，因此这个层面无路可走。
在生成的html层面，只能在页头生成一些可跳转的a标签，a标签指向锚点似乎可以达到跳转的效果（本人并没有尝试过，只是在查阅文章时看到），但即便可行，也只是在pdf页面内部生成了可供点击的跳转链接，并不能达到平时使用pdf文件时的目录效果。
另外一个就是保持现有的pdf生成，通过其他的软件来对pdf进行二次修改（我在网上找到的所有添加目录的方式都是使用软件）将目录加入pdf。
可见以上三种方式都无法很好地解决问题，因此目前无法实现这个功能，并且由于pdf这个格式并不如markdown开源开放，我对pdf格式的了解也非常贫乏，可能需要继续深入了解pdf的内部构成才能发现其他方案。
最后感谢你提出的issues，我会继续寻找解决方案。

**Comment by hhhaiai** [comment]
赞！  我最近也找找解决方案

**Comment by tisttsf** [comment]
> 赞！ 我最近也找找解决方案

找到方法了吗.

**Comment by JabinGP** [comment]
通过 chrome 渲染得到的 pdf 文件似乎没有自带目录，一个似乎可行的思路是在 markdown 解析阶段收集标题信息，再讲生成的 pdf 通过 gofpdf 打开加入标题信息再生成新的 pdf 。

**Comment by tisttsf** [comment]
> gofpdf

好的我试试,然后就是代码自动换行的问题,pdf中设置了固定的尺寸,代码如果宽度过长,就会被截断丢失内容,html格式阶段不会有这样的问题,如果不自己换好行的话解决起来好像也很麻烦.

**Comment by JabinGP** [comment]
@tisttsf 代码换行highlightjs的特性，目前我没有找到让highlightjs自动换行的设置，如果需要打印自动换行的话，可以考虑弃用highlightjs（这是主题文件中的html模板决定的），改用其他能够自动换行的显示方式。

**Comment by tisttsf** [comment]
> @tisttsf 代码换行highlightjs的特性，目前我没有找到让highlightjs自动换行的设置，如果需要打印自动换行的话，可以考虑弃用highlightjs（这是主题文件中的html模板决定的），改用其他能够自动换行的显示方式。

好的谢谢你的回答,感谢你的项目,很好用

**Comment by hhhaiai** [comment]
谢谢作者
