### ISSUE TITLE
0.7.0版本 怎么转换不了html文件

### ISSUE THREAD

**Issue by CoderLiXiaoJie** [JabinGP/mdout#30]
<img width="724" alt="WeChatd5e0adfce5d2a8d7e77186fa2cc08eca" src="https://user-images.githubusercontent.com/87177891/125384197-22676600-e3cb-11eb-84fe-3bca74f0d4fe.png">
感觉被识别为url了

**Comment by CoderLiXiaoJie** [comment]
mac系统

**Comment by JabinGP** [comment]
问题在我的 mbp2020 10.15.7 上复现，正在着手修复。

**Comment by JabinGP** [comment]
尝试使用[0.7.1版本](https://github.com/JabinGP/mdout/releases/tag/0.7.1)。

**Comment by CoderLiXiaoJie** [comment]
好的，修复了
