### ISSUE TITLE
mdout，多次调用md生成pdf有时候会卡住（不处理的话一直卡住），请问这是什么问题

### ISSUE THREAD

**Issue by SubePython** [JabinGP/mdout#36]
![image](https://user-images.githubusercontent.com/39877932/144980373-ce2a798c-5d1b-4a06-a048-3f05bd96476e.png)

**Comment by SubePython** [comment]
版本是0.7.2

**Comment by JabinGP** [comment]
能否描述一下如何复现该问题。

**Comment by JabinGP** [comment]
由于长时间没有收到相关反馈，我先将该issue关闭
