### ISSUE TITLE
能否增加书签和代办事项的支持？

### ISSUE THREAD

**Issue by liukong** [JabinGP/mdout#37]
先道声谢谢，帮我很大的忙。我发现 mdout 不支持代办事项和书签点击跳转， typort 生成的 pdf 可以。能不能完善一下？或者怎么自主扩展支持？

- [ ]  代办事项
- [ ] 书签

**Comment by JabinGP** [comment]
1. 书签的功能不太好做，短期内应该不会实现

**Comment by JabinGP** [comment]
2. 待办事项我看了一下，目前markdown解析以后生成的html中，代办事项的部分如下

**Comment by JabinGP** [comment]
2. 待办事项我看了一下，目前markdown解析以后生成的html中，代办事项的部分如下
```html
<ul>
<li>[ ] 1</li>
<li>[x] 2</li>
</ul>
```

如果可以转化为类似下面的结构则可以实现期望效果

```
<ul>
<li><input type="checkbox">1</li>
<li><input type="checkbox"  checked>2</li>
</ul>
```

最简单的方法就是在使用的主题文件中，编写js遍历dom元素，找到 ul -> li 后判断里面内容是否存在 [ ] 或者 [x]，然后替换为如上格式即可。

**Comment by liukong** [comment]
我只懂一点点js，搞不定。期待您的更新。

**Comment by liukong** [comment]
我只懂一点点js，搞不定。期待您的更新。

**Comment by JabinGP** [comment]
我周末找时间试一下更新主题

**Comment by liukong** [comment]
多谢！多谢！

**Comment by JabinGP** [comment]
@liukong 待办事项的展示已经在 默认github风格主题 0.1.2 版本中支持

https://github.com/JabinGP/mdout-theme-github/archive/refs/tags/0.1.2.zip
可以使用该压缩包中内容手动替换原有主题包中内容更新使用

**Comment by liukong** [comment]
辛苦！不过有点小瑕疵，输出是待办事项的列表，应该仅仅是待办事项。

**Comment by JabinGP** [comment]
在主题包中的 index.html 中可以给元素设置一些css属性来达到你的效果，例如在 0.1.2 版本的 github 风格主题中，将 index.html 的89行下增加该行代码：
```js
ele.setAttribute("style", "list-style:none")
```

**Comment by liukong** [comment]
谢谢，明白了。我自己尝试加个样式，行距太宽了。
