### ISSUE TITLE
代码块未自动换行

### ISSUE THREAD

**Issue by Alonglang** [JabinGP/mdout#4]
代码块单行较长，在typora中会自动换行，
转为html后无自动换行，导致超出打印范围的部分在pdf打印输出时丢失

**Comment by vernon2gh** [comment]
您好，我也出现这个问题，PC机是ubuntu20.04，请问这个BUG已经修复了吗？

**Comment by JabinGP** [comment]
你好，这是highlightjs的特性，原本用于网页浏览的，由于我并没有找到能够开启自动换行的选项，暂时无法解决。

**Comment by JabinGP** [comment]
@vernon2gh @Alonglang @tisttsf 代码换行问题已经在 mdout-theme-github-0.1.1 中解决，可以使用 mdout-0.7.0 配合 mdout-theme-github-0.1.1 使用，[主题安装教程点这](https://github.com/JabinGP/mdout/blob/master/install.md#41-%E9%80%9A%E8%BF%87-mdout-%E5%86%85%E7%BD%AE%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96%E4%B8%BB%E9%A2%98%E5%8C%85)。
