### ISSUE TITLE
本地图片没法显示

### ISSUE THREAD

**Issue by WHF-ZUCC** [JabinGP/mdout#40]

**Comment by WHF-ZUCC** [comment]
markdown![image](https://user-images.githubusercontent.com/80940816/188107500-7ba037d7-e87c-46da-aeb6-ac538247ec81.png)
![image](https://user-images.githubusercontent.com/80940816/188107550-b27daf0f-8abc-4a63-b5a5-963a1a3cf514.png)

**Comment by JabinGP** [comment]
可以使用正斜杠

**Comment by JabinGP** [comment]
img/person-company.jpg

**Comment by WHF-ZUCC** [comment]
反斜杠 序列化的时候换成了别的字母，我直接替换了
