### ISSUE TITLE
ip字符会被自动打上超链接

### ISSUE THREAD

**Issue by WHF-ZUCC** [JabinGP/mdout#44]
例如md里有一段是 `1.1.1.1`，会被解析成 `<a href="http://1.1.1.1">1.1.1.1</a>`

**Comment by WHF-ZUCC** [comment]
经过测试，不是`russross/blackfriday`的问题，可以看一下为什么吗？

**Comment by JabinGP** [comment]
https://gitlab.com/golang-commonmark/markdown#usage

**Comment by JabinGP** [comment]
应该是 [golang-commonmark](https://gitlab.com/golang-commonmark) 的默认行为

**Comment by WHF-ZUCC** [comment]
谢谢，加上下面代码里的注释 就好了

```
md := markdown.New(
		markdown.XHTMLOutput(true),
		markdown.HTML(true),
		// markdown.Linkify(false),
	)
```
