### ISSUE TITLE
数学公式换行问题

### ISSUE THREAD

**Issue by happysnaker** [JabinGP/mdout#46]
环境：lwabish/mdout:chinese

这是 md 内容：
![image](https://user-images.githubusercontent.com/73147033/196878795-d34ec8e5-2f40-4cbb-940b-61732b7f0f03.png)

最终的结果似乎不太正确：
![image](https://user-images.githubusercontent.com/73147033/196878886-f3bc43ee-86b7-47ea-a0c4-e4e9e406c22c.png)

请问我应该怎么做？

**Comment by sczfaker** [comment]
```
$$
\sum_{k=0}^{n}(-1)^k
$$
$$
\sum_{k=0}^{n}(-1)^k
$$
$$
\sum_{k=0}^{n}(-1)^k
$$
```
这样?
