### ISSUE TITLE
displayed math 没有正常解析 换行有问题

### ISSUE THREAD

**Issue by Tony-is-here** [JabinGP/mdout#6]

**Comment by JabinGP** [comment]
麻烦提供一下有问题的md源码，让我进行测试一下。

**Comment by Tony-is-here** [comment]
$$
\bar A \cdot \bar B + A \cdot \bar B+ A \cdot B \\
=\bar A \cdot \bar B + A \cdot \bar B+ A \cdot B + \bar B \cdot A \\
=\bar B \cdot (\bar A + A) +A \cdot (B + \bar B) \\
=\bar B + A
$$

我看到您生成的html文件里没有这一行

displayMath: [ ['$$','$$'], ["\[","\]"] ]

是不是这个原因？

On Apr 16, 2020, at 3:49 PM, JabinGP <notifications@github.com<mailto:notifications@github.com>> wrote:



麻烦提供一下有问题的md源码，让我进行测试一下。

**Comment by Tony-is-here** [comment]
您好，另外markdown 内嵌的html标签也无法正常解析。例如: <br>

多多麻烦

On Apr 16, 2020, at 3:49 PM, JabinGP <notifications@github.com<mailto:notifications@github.com>> wrote:



麻烦提供一下有问题的md源码，让我进行测试一下。

**Comment by JabinGP** [comment]
你好，内嵌的html标签无法解析是因为`golang-commonmark`这个解析器默认没有开启解析，非常抱歉没有考虑到这个问题，在新版中会添加开关选项。

**Comment by Tony-is-here** [comment]
> 你好，内嵌的html标签无法解析是因为`golang-commonmark`这个解析器默认没有开启解析，非常抱歉没有考虑到这个问题，在新版中会添加开关选项。

哇，是这样，感谢。内嵌latex换行的问题您那边能复现吗？

**Comment by JabinGP** [comment]
@Tony-is-here 
你好，经过我的测试，发现late无法换行的原因有以下两点：
1. 你的源码双反斜杠被markdown解析之后变成了单反斜杠，失去了原有的语义，这个可以输入四个反斜杠解决。
2. 为了限制包体积，我使用了Github上一个开源的精简包，之前测试可以正常显示，但是现在发现这个包无法完成换行功能，由于`MathJax`完整包过于庞大，我也很难着手亲自精简，如果需要使用，可以通过引入完整的CDN包来解决，除此之外我正尝试使用`mermaid`替换`MathJax`，`mermaid`的完整包大小完全可以接受，目前正在进行尝试，但由于本人并不使用`latex`，在测试上难免疏忽，如果可以，请提供一些`latex`公式的源码和期望的输出图片给我，便于我进行测试，谢谢。

**Comment by JabinGP** [comment]
@Tony-is-here
你好，经过我的测试，发现late无法换行的原因有以下两点：

1. 你的源码双反斜杠被`markdown`解析之后变成了单反斜杠，失去了原有的语义，这个可以输入四个反斜杠解决。
2. 为了限制包体积，我使用了Github上一个开源的精简包，之前测试可以正常显示，但是现在发现这个包无法完成换行功能，由于`MathJax`完整包过于庞大，我也很难着手亲自精简，如果需要使用，可以通过引入完整的CDN包来解决，除此之外我正尝试使用`KaTex`替换`MathJax`，目前正在进行尝试，但由于本人并不使用`latex`，在测试上难免疏忽，如果可以，请提供一些`latex`公式的源码和期望的输出图片给我，便于我进行测试，谢谢。

**Comment by Tony-is-here** [comment]
明白了，多谢！
我也只是用latex随便写写作业什么的，暂时没有遇到其他问题。
才接触编程不久，对go语言不了解，不好意思没有办法提供更多的帮助。

自己模仿typora的主题写了一个模版，如果能有帮助的话，那就太好了。
[mytheme.zip](https://github.com/JabinGP/mdout/files/4503727/mytheme.zip)

**Comment by JabinGP** [comment]
我测试使用KaTeX并解决了一些问题，应该是可以替换的。你可以把你正在使用的主题包发给我，我帮你修改一下。

**Comment by Tony-is-here** [comment]
主题包粘贴在下面了，麻烦！

https://github.com/JabinGP/mdout/files/4503727/mytheme.zip

**Comment by JabinGP** [comment]
[mytheme.zip](https://github.com/JabinGP/mdout/files/4526632/mytheme.zip)
@Tony-is-here 你好，我已经帮你替换成了KaTex，在1w行数学公式源代码、2666频率8G内存、i5 7500的测试下，解析大概需要15秒，生成pdf共175页大概需要40秒，其中没有出现公式渲染不到位的情况。
换行问题请使用四斜杠代替双斜杠。
如果有其他问题请及时反馈。

**Comment by Tony-is-here** [comment]
感谢！
