### ISSUE TITLE
markdown 使用 <img> 标签转为pdf不生效？有什么办法处理吗

### ISSUE THREAD

**Issue by cuzz1** [JabinGP/mdout#7]
```
<center><img src="http://img.xxx.png" width="80%" /></center>
```

**Comment by JabinGP** [comment]
你好，首先非常抱歉由于个人原因没能及时关注该issues。
我使用ind.html作为示例测试，文件内容如下：
```html
<center><img src="https://www.baidu.com/img/flexible/logo/pc/result@2.png" width="80%" /></center>
```
经过`mdout ind.html`后生成的pdf拥有正常显示的图片，pdf如下图，目前无法成功复现你的问题。
![image](https://user-images.githubusercontent.com/32405671/97657959-286c1f80-1aa6-11eb-8364-daacb2e4823e.png)
如果问题依然存在，希望可以提供更为详细的测试说明。

**Comment by cuzz1** [comment]
我是在markdown 文件中插入图片，使用html标签
