### ISSUE TITLE
转换有问题。  说没设置环境变量 设置了啊

### ISSUE THREAD

**Issue by hhhaiai** [JabinGP/mdout#9]
2021/01/14 19:56:39 exec: "google-chrome": executable file not found in $PATH
2021/01/14 19:56:39 开始保存文件
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa4f302]

goroutine 1 [running]:
github.com/JabinGP/mdout/cmdrun.MdToPdfE(0x7ffff32a116e, 0x16, 0x11a7a80, 0x3, 0x0)
        /Users/jabin/Code/GithubProjects/mdout/cmdrun/md_pdf.go:104 +0x802
github.com/JabinGP/mdout/cmd.rootRunE(0x119d620, 0xc000188ca0, 0x1, 0x1, 0x0, 0x0)
        /Users/jabin/Code/GithubProjects/mdout/cmd/root.go:167 +0x2ef
github.com/spf13/cobra.(*Command).execute(0x119d620, 0xc00000c0b0, 0x1, 0x1, 0x119d620, 0xc00000c0b0)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x119d620, 0x40576f, 0xc000090058, 0x0)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/JabinGP/mdout/cmd.Execute()
        /Users/jabin/Code/GithubProjects/mdout/cmd/root.go:49 +0x2d
main.main()
        /Users/jabin/Code/GithubProjects/mdout/main.go:8 +0x20

**Comment by JabinGP** [comment]
Windows 系统的话可以试试通过命令行执行  `chrome.exe`  能不能启动浏览器，如果不能说明环境变量没设置好，Linux 的话试试 `google-chrome`。
另外，这是寻找可执行文件的源码，来源于 [chromedp/chromedp/blob/v0.5.4/allocate.go](https://github.com/chromedp/chromedp/blob/v0.5.4/allocate.go)，可以结合排查问题：

```go
func findExecPath() string {
	for _, path := range [...]string{
		// Unix-like
		"headless_shell",
		"headless-shell",
		"chromium",
		"chromium-browser",
		"google-chrome",
		"google-chrome-stable",
		"google-chrome-beta",
		"google-chrome-unstable",
		"/usr/bin/google-chrome",

		// Windows
		"chrome",
		"chrome.exe", // in case PATHEXT is misconfigured
		`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`,
		`C:\Program Files\Google\Chrome\Application\chrome.exe`,
		filepath.Join(os.Getenv("USERPROFILE"), `AppData\Local\Google\Chrome\Application\chrome.exe`),

		// Mac
		"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
	} {
		found, err := exec.LookPath(path)
		if err == nil {
			return found
		}
	}
	// Fall back to something simple and sensible, to give a useful error
	// message.
	return "google-chrome"
}
```

**Comment by hhhaiai** [comment]
可以打开的

**Comment by hhhaiai** [comment]
Windows 系统，命令行执行 chrome.exe和google-chrome.exe(chrome.exe的软链接)

**Comment by hhhaiai** [comment]
更新了最新版本，我再测试下。还是不行。

`2021/01/15 10:53:51 exec: "google-chrome": executable file not found in $PATH
2021/01/15 10:53:51 开始保存文件
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa4f302]

goroutine 1 [running]:
github.com/JabinGP/mdout/cmdrun.MdToPdfE(0x7ffff70b998e, 0x16, 0x11a7a80, 0x3, 0x0)
        /Users/jabin/Code/GithubProjects/mdout/cmdrun/md_pdf.go:104 +0x802
github.com/JabinGP/mdout/cmd.rootRunE(0x119d620, 0xc0001a0c90, 0x1, 0x1, 0x0, 0x0)
        /Users/jabin/Code/GithubProjects/mdout/cmd/root.go:167 +0x2ef
github.com/spf13/cobra.(*Command).execute(0x119d620, 0xc0000aa030, 0x1, 0x1, 0x119d620, 0xc0000aa030)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x119d620, 0x40576f, 0xc000090058, 0x0)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jabin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/JabinGP/mdout/cmd.Execute()
        /Users/jabin/Code/GithubProjects/mdout/cmd/root.go:49 +0x2d
main.main()
        /Users/jabin/Code/GithubProjects/mdout/main.go:8 +0x20
`

**Comment by hhhaiai** [comment]
windows 有git、cygwin等环境。并且设置了环境变量，为啥一直识别成 google-chrome， 这部分判断有问题吧。 判断成linux了

```
// Unix-like
		"headless_shell",
		"headless-shell",
		"chromium",
		"chromium-browser",
		"google-chrome",
		"google-chrome-stable",
		"google-chrome-beta",
		"google-chrome-unstable",
		"/usr/bin/google-chrome",
```

**Comment by JabinGP** [comment]
注意函数的最后缺省返回了 "google-chrome" ，说明该函数无法找到你的可执行文件，并不是将你识别成了 Linux 。

**Comment by JabinGP** [comment]
如果你有 go 语言环境，或许你可以很方便地测试一下 `findExecPath()`  为什么不能找到你的 chrome.exe 。

**Comment by hhhaiai** [comment]
刚换电脑没go环境。 是否需要联调。加个联系方式？

**Comment by hhhaiai** [comment]
+我Q 2158075194
